// Keys shared by app, core validation, and platform errors.
extension L10n {
    public enum Key: String, CaseIterable, Sendable {
        case untitled
        case fieldName
        case fieldOrder
        case fieldActive
        case fieldMissingActive
        case fieldMaximized
        case fieldWindowFrame
        case fieldPaneFrame
        case fieldFolder
        case fieldSettings
        case projectTooLarge
        case maximizeRestore
        case minimize
        case close
        case resizePaneAccessibility
        case emptyWorkspace
        case openProject
        case saveProject
        case addExplorer
        case addWindow
        case newProcess
        case tileColumns
        case tileRows
        case cascade
        case open
        case saveReadOnly
        case saveFailed
        case saveChangesQuestion
        case saveChangesDetail
        case saveAs
        case save
        case discard
        case cancel
        case reacquireFailed
        case hiddenItems
        case back
        case forward
        case up
        case refresh
        case folderPath
        case searchFolder
        case columnName
        case columnModified
        case columnKind
        case columnSize
        case fileList
        case breadcrumbs
        case resizeTree
        case loading
        case openFileFailed
        case watchUnavailable
        case folderPermission
        case folderMissing
        case folderTree
        case home
        case downloads
        case computer
        case volumes
        case treeOpenFailed
        case recentProjects
        case recoverySaveFailed
        case instanceFailed
        case about
        case hideApp
        case quitApp
        case menuFile
        case newExplorer
        case newMDIWindow
        case launchProcess
        case chooseFolder
        case openSelectionInPane
        case closeExplorer
        case closeMDIWindow
        case menuProject
        case newProject
        case chooseProject
        case switchProject
        case projectNewProcess
        case saveProjectMenu
        case saveAsMenu
        case reacquireProject
        case recoverSession
        case menuEdit
        case undo
        case undoFileAction
        case undoReplacementUnavailable
        case undoIncompleteUnavailable
        case undoFileScope
        case undoReplacementDetail
        case undoIncompleteDetail
        case moveAction
        case cut
        case copy
        case paste
        case selectAll
        case menuView
        case toggleFavorite
        case menuGo
        case parentFolder
        case goToPath
        case menuWindow
        case nextExplorer
        case previousExplorer
        case maximizePane
        case minimizePane
        case movePane
        case resizePane
        case cascadeMenu
        case menuHelp
        case shortcutList
        case diagnostics
        case shortcutsTitle
        case shortcutsBody
        case switchProjectTitle
        case openProjectWindow
        case openProjectFailed
        case recentUpdateFailed
        case noRecentProjects
        case recoveryWriteFailed
        case noRecovery
        case chooseRecovery
        case recoveryDetail
        case recover
        case recoveryFailed
        case kindLink
        case kindPackage
        case kindFolder
        case kindFile
        case storageLocked
        case storageExternalChange
        case storageHardLink
        case storageNotLocal
        case storageInvalidFile
        case storageClosed
        case unsupportedProject
        case invalidProject
        case movePaneAccessibility
        case activePaneAccessibility
        case workspaceTitle
        case moveHint
        case resizeHint
        case restorePane
        case recoveredName
        case readOnlyTitle
        case openFailed
        case extensionKind
        case diagnosticsBody
        case languageMenu
        case languageSystem
        case languageEnglish
        case languageJapanese
        case languageNextLaunch
        case languageNextLaunchDetail
        case invalidItemName
        case invalidOperationLocation
        case fileOperationBusy
        case fileOperationConflict
        case fileOperationSourceChanged
        case fileOperationDestinationChanged
        case fileOperationInsideSource
        case fileOperationUnsupported
        case fileUndoChanged
        case fileUndoUnavailable
        case copiedItemName
        case moveCopyRetained
        case operationOriginalRetained
        case replacementBackupRetained
        case itemCount
        case shortcutPreset
        case shortcutExplorer
        case shortcutMac
        case shortcutAlternative
        case shortcutsBodyMac
        case fieldSession
        case trashedWithoutUndo
        case fileCommittedWarning
        case retainedOperationsMenu
        case retainedOperationsDetail
        case noRetainedOperations
        case revealRetainedOperations
        case cutRequestUnavailable
        case cutRequestChanged
        case newFolder
        case renameItem
        case moveToTrash
        case copyPath
        case itemName
        case createItem
        case renameAction
        case newFolderPrompt
        case renamePrompt
        case copyingFiles
        case cuttingFiles
        case movingFiles
        case trashingFiles
        case undoingFiles
        case preparingFiles
        case fileProgress
        case cancellingFiles
        case fileOperationFailed
        case fileOperationResults
        case fileResultCounts
        case fileOperationCancelled
        case fileConflictTitle
        case fileConflictDetail
        case folderConflictDetail
        case replaceItem
        case skipItem
        case keepBoth
        case trashConfirm
        case trashConfirmDetail
        case clipboardCopyStatus
        case clipboardCutStatus
        case foreignClipboardCopy
        case fileOperationWait
        case fileOperationWaitDetail
        case showFileProgress
        case cancelFileOperation
        case contextOpen
        case clipboardUnavailable
        case selectedCount
        case windowCount
    }
}
